### ISSUE TITLE
Failed to create table with two different groups from 3 DNs

### ISSUE THREAD

**Issue by duerwuyi** [Tencent/TBase#155]
I used k8s with kubeblocks to create a cluster with 3 DNs. I changed the `values.yaml` in `OpenTenBase\example\kubernetes\opentenbase-cluster\values.yaml` and removed `vsacle-values.yaml` and `add-dn-nodes.yaml` because I do not know whether this two files have any impacts on the cluster.
Then `helm install otb ./opentenbase-cluster` succeeded.
Then I tried to create 2 groups:
```sql
postgres=# select * from pgxc_node;
 node_name | node_type | node_port | node_host | nodeis_primary | nodeis_preferred |   node_id   |  node_cluster_name
-----------+-----------+-----------+-----------+----------------+------------------+-------------+---------------------
 a_one     | G         |     50001 | otb-gtm   | t              | f                | -1343982441 | opentenbase_cluster
 dn_0      | D         |      5432 | otb-dn-0  | f              | f                |  1485981022 | opentenbase_cluster
 dn_1      | D         |      5432 | otb-dn-1  | f              | f                | -1300059100 | opentenbase_cluster
 dn_2      | D         |      5432 | otb-dn-2  | f              | f                | -1051926843 | opentenbase_cluster
 cn_0      | C         |      5432 | otb-cn-0  | f              | f                | -1541982360 | opentenbase_cluster
(5 rows)
postgres=# create default node group default_group with(dn_0, dn_1);
CREATE NODE GROUP
postgres=# create sharding group to group default_group;
CREATE SHARDING GROUP
postgres=# clean sharding;
CLEAN SHARDING
postgres=# create node group single_group with(dn_2);
CREATE NODE GROUP
postgres=# clean sharding;
CLEAN SHARDING
postgres=# select * from pgxc_group;
  group_name   | default_group | group_members
---------------+---------------+---------------
 default_group |             1 | 16384 16386
 single_group  |             0 | 16388
(2 rows)
```

Then I failed to create table:
```sql
postgres=# create table foo(id bigint, str text) distribute by shard(id);
ERROR:  node:dn_2, backend_pid:4192, nodename:dn_2,backend_pid:4192,message:[GetShardNodes_DN]corrupted catalog, no shard group of 16390 found
```
Is it a bug? Or maybe I executed some unexpected query?

Btw, it helps me a lot if someone can tell me how to create multiple groups(especially single groups for single tables), alter, delete groups, and what is the meaning of `create sharding group to group default_group;` and `clean sharding;`?

**Comment by duerwuyi** [comment]
My `value.yaml`:
```yaml
terminationPolicy: Delete

## cluster settings for opentenbase cluster
gtm:
  ## @param gms.replicas data replicas of gms instance
  ## Default value is 3, which means a paxos group: leader, follower, follower
  replicas: 1
  ## @param gms.resources
  ## resource management for gms component
  ## more info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"
  ## Enable persistence using Persistent Volume Claims
  ## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    ## @param shard[*].persistence.enabled Enable persistence using Persistent Volume Claims
    ##
    enabled: true
    ## `data` volume settings
    ##
    data:
      ## @param shard[*].persistence.data.storageClassName Storage class of backing PVC
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      storageClassName:
      ## @param shard[*].persistence.size Size of data volume
      ##
      size: 20Gi

dn:
  -
    ## @param dn[*].replicas data replicas of each DN instance
    ## Default value is 3, which means a paxos group: leader, follower, follower
    replicas: 1
    ## @param dn[*].resources
    ## resource management for dn component
    ## more info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "1Gi"
    ## Enable persistence using Persistent Volume Claims
    ## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
    ##
    persistence:
      ## @param shard[*].persistence.enabled Enable persistence using Persistent Volume Claims
      ##
      enabled: true
      ## `data` volume settings
      ##
      data:
        ## @param shard[*].persistence.data.storageClassName Storage class of backing PVC
        ## If defined, storageClassName: <storageClass>
        ## If set to "-", storageClassName: "", which disables dynamic provisioning
        ## If undefined (the default) or set to null, no storageClassName spec is
        ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
        ##   GKE, AWS & OpenStack)
        ##
        storageClassName:
        size: 20Gi
  - replicas: 2
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "1Gi"
    persistence:
      enabled: true
      data:
        storageClassName:
        size: 20Gi
  - replicas: 3
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "1Gi"
    persistence:
      enabled: true
      data:
        storageClassName:
        size: 20Gi
cn:
  -
    ## @param cn.replicas number of cn nodes
    replicas: 1
    ## @param cn.resources
    ## resource management for cn component
    ## more info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "1Gi"
    persistence:
      ## @param shard[*].persistence.enabled Enable persistence using Persistent Volume Claims
      ##
      enabled: true
      ## `data` volume settings
      ##
      data:
        ## @param shard[*].persistence.data.storageClassName Storage class of backing PVC
        ## If defined, storageClassName: <storageClass>
        ## If set to "-", storageClassName: "", which disables dynamic provisioning
        ## If undefined (the default) or set to null, no storageClassName spec is
        ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
        ##   GKE, AWS & OpenStack)
        ##
        storageClassName:
        ## @param shard[*].persistence.size Size of data volume
        ##
        size: 20Gi
```
